package com.example.springboot.config;

public enum ReturnDataEnum {


        PERMISSION_DENIED(20001, "权限不足"),
        RECORD_IS_DELETED(20002, "元素已删除"),
        PARENT_PERMISSION_DENIED(20003, "对上级元素的权限不足"),
        HAS_CHILDREN(20004, "有下级元素，不可删除"),
        COMPANY_MISSING_OR_EMPTY(20011, "Company is missing or empty."),
        WORKSPACE_NOT_FOUND_BY_DOMAIN(20012, "Could not find workspace by domain."),
        COMPANY_NOT_EXIST(20013, "公司不存在"),
        GROUP_NOT_EXIST(20021, "Could not find group."),
        INVALID_PASSPORT_PARENT(20022, "账户上级非法"),
        NAME_MISSING_OR_EMPTY(20031, "Name is missing or empty."),
        NICKNAME_MISSING_OR_EMPTY(20032, "Nickname is missing or empty."),
        XCX_LOGIN_NO_CODE(20033, "小程序用户未授权（无code）"),
        USERNAME_MISSING_OR_EMPTY(20101, "Username is missing or empty."),
        PASSWORD_MISSING_OR_EMPTY(20102, "Password is missing or empty."),
        MAIL_OR_NAME_MISSING_OR_EMPTY(20104, "缺失邮箱或名称"),
        PASSWORD_MISMATCH(20130, "账户与密码不匹配"),
        PASSPORT_ID_EMPTY(20131, "passportId 为空"),
        MEMBER_NOT_FOUND_BY_MAIL(20132, "A member with the specified email was not found."),
        PASSPORT_EXISTS_BY_MAIL(20133, "A passport with this email does exist!"),
        NEW_PWD_IS_SAME_AS_OLD(20136, "The new password is the same as original password."),
        PWD_STRENGTH_NOT_ENOUGH(20137, "密码强度不够：需6-16位，包含字母和数字"),
        PASSPORT_INVALID(20140, "此账户已被禁用"),
        PASSPORT_TOKEN_NOT_EXIST(20141, "找不到token-id"),
        ACCESS_TOKEN_INVALID_OR_EMPTY(20180, "Access token is invalid or empty."),
        ACCESS_TOKEN_EXPIRED(20181, "Access token expired."),
        REFRESH_TOKEN_INVALID_OR_EMPTY(20182, "Refresh token is invalid or empty."),
        REFRESH_TOKEN_EXPIRED(20183, "Refresh token expired."),
        SECRET_TOKEN_INVALID_OR_EMPTY(20184, "Secret token is invalid or empty."),
        PASSPORT_NOT_EXIST(20201, "无法找到此账户"),
        PASSPORT_TYPE_NOT_PERSON(20202, "The passport is not a person."),
        PASSPORT_TYPE_NOT_COMPANY(20203, "The passport is not a company."),
        IP_LOCKED(20204, "此 IP 已被禁用"),
        CAPTCHA_EXPIRED(20205, "验证码已过期"),
        CAPTCHA_WRONG(20206, "验证码错误"),
        OFFICE_NOT_EXIST(20301, "Could not find office."),
        ARTICLE_NOT_EXIST(20302, "Cannot find article."),
        OFFICE_ROOM_NOT_EXIST(20303, "Could not find office-room."),
        MEETING_TIME_CLASH(20304, "会议室时间有冲突"),
        WATERMARK_FAILED(21002, "Failed to created watermark file."),
        DOWNLOAD_FAILED_BEFORE_WATERMARK(21004, "Filed to download the file before add watermark."),
        FORBIDDEN_DELETE_PERSONAL_FOLDER(21005, "不能删除自己的个人文件夹"),
        FORBIDDEN_SHARE_WITHOUT_AGREEMENT(21006, "该文件禁止无协议分享"),
        FILE_IS_NOT_DIRECTORY(21007, "The parent is not a directory."),
        FILE_NOT_EXIST(21008, "Cannot find the file."),
        FORBIDDEN_SHARE_WITHOUT_WATERMARK(21009, "该文件禁止无水印分享"),
        VERSION_NOT_EXIST(21010, "Cannot find the version."),
        QINIU_NOT_EXIST(21011, "找不到七牛链接"),
        FILE_FORMAT_INVALID(21012, "文件格式非法或不支持"),
        SHARE_NOT_EXIST(21013, "Cannot find the share."),
        SHARE_LINK_NOT_EXIST(21014, "此 public 分享没有 link 信息"),
        CANNOT_UPDATE_PRIVATE_SHARE(21015, "私有分享不允许修改"),
        FILE_MOVE_SAME_PARENT(21017, "目标位置与原位置相同"),
        INCORRECT_SHARE_PASSWORD(21018, "文件密码不正确。"),
        PATH_IN_FILE_WRONG(21019, "文件的路径元素错误"),
        FORBIDDEN_MOVE_TO_DESCENDANT(21020, "不能移动到自己的子文件夹里"),
        PRIVATE_SHARE_EXISTS(21021, "私有分享已经存在"),
        FILE_FORMAT_INCOMPATIBLE(21022, "文件格式不一致"),
        SHARE_IS_INVALID(21023, "该分享禁止访问"),
        FILE_NO_VERSION(21026, "文件没有版本"),
        FILE_NO_ACTIVE_VERSION(21027, "文件没有活动版本"),
        SHARE_NO_ACTIVE_VERSION(21028, "分享没有活动版本"),
        ACTIVE_FOR_FILE_AND_SHARE_DIFF(21029, "分享的活动版本与文件的不同"),
        VERSION_IS_RUNNING(21030, "版本的相关数据仍在处理中"),
        NO_PRIVATE_SHARE(21031, "无私有分享"),
        FORBIDDEN_PUBLIC_SHARE(21032, "文件不允许public分享"),
        FILE_ONLY_ONE_VERSION(21033, "文件只有一个版本，不允许删除"),
        SHOULD_NOT_SHARE(21034, "这是您自己的文件，无需创建private分享"),
        PDF_OPEN_PASSWORD_WRONG(21035, "PDF文件的打开密码错误"),
        VERSION_IS_FAILED(21036, "版本处理失败（上传？拆分？请检查日志）"),
        NEED_SIGN(21037, "必须同意协议"),
        DOCUMENT_TEMPLATE_NOT_EXIST(21038, "文档模板不存在"),
        DOCUMENT_NOT_EXIST(21039, "文档不存在"),
        ORDER_NOT_EXIST(22000, "订单不存在"),
        ORDER_NOT_PAID(22001, "订单不在已付款状态"),
        SALE_REFUND_NOT_EXIST(22002, "没有退款记录"),
        SALE_REFUND_NOT_APPLY(22003, "不在申请退款状态"),
        ORDER_NOT_RETURNING(22004, "订单不在待退款状态"),
        ORDER_DETAIL_NOT_EXIST(22005, "订单详细不存在"),
        ORDER_NOT_CHECKED(22006, "订单不在已审核状态"),
        WX_CODE_IS_MISSING(23000, "code 参数没有"),
        VISIT_BY_IS_MISSING(23001, "visitBy 参数没有"),
        WX_USER_INFO_INVALID(23002, "微信用户信息缺失");

        public final Integer code;
        public final String msg;

        private ReturnDataEnum(Integer code, String msg) {
            this.code = code;
            this.msg = msg;
        }
    }


